### ISSUE TITLE
getting errorrs on rss feeds

### ISSUE THREAD

**Issue by mattherick** [bborn/communityengine#285]
If I call

    http://localhost:3000/users/my-user/comments.rss

I get following error..

    uninitialized constant ResourceFeeder::Rss::Builder
    app/controllers/comments_controller.rb:29:in `block (2 levels) in index'
    app/controllers/comments_controller.rb:25:in `index'

The same problem exists on your demo-page:

    http://demo.communityengine.org/users/test-frick-web/comments.rss

I get an 500 error:

    We're sorry, but something went wrong.

Any idea where I could fix this issue?

UPDATE:
You are using "Builder::XmlMarkup"..and it seems that this causes the error. The rss stuff is over 6 years old, it seems that your class was removed in the newer rails versions.. maybe we could use https://github.com/jimweirich/builder to fix it?

UPDATE2:
I could fix the problem with simple require builder - it is already in the Gemfile.lock - it is a dependency of actionpack..

lib/resource_feeder/atom.rb
lib/resource_feeder/rss.rb

    require "builder"

Should I also add the "builder" gem to the gemspec as an dependency?

**Comment by mattherick** [comment]
Should be fixed with PR #284
